### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by Hamid-Najafi** [mauricioabreu/nginx_rtmp_prometheus#2]
Do you have any prepared dashboard for this exporter?

**Comment by mauricioabreu** [comment]
@Hamid-Najafi No. Are you looking for something specific?

**Comment by Hamid-Najafi** [comment]
I mean gragafa dashboard as GUI for this exporter.
These is a node app which is not prometheus based

https://github.com/3m1o/nginx-rtmp-monitoring

**Comment by mauricioabreu** [comment]
@Hamid-Najafi sorry but I don't have a prepared Grafana dashboard for these metrics.

I ended up creating some Grafana panels but I'm on vacation without access to them.
