### ISSUE TITLE
Compilation on Ubuntu 20.04 not succesful

### ISSUE THREAD

**Issue by royvandongen** [mauricioabreu/nginx_rtmp_prometheus#3]
Since there are no defined dependencies or prerequisites i had to install multiple dependencies before running the make command. The make command itself resulted in the following error;

`/tmp/nginx_rtmp_prometheus-master$ make
>> checking code style
>> checking license header
>> running golangci-lint
GO111MODULE=on go list -e -compiled -test=true -export=false -deps=true -find=false -tags= -- ./... > /dev/null
GO111MODULE=on /home/REDACTED/go/bin/golangci-lint run  ./...
ERRO Deadline exceeded: try increase it by passing --deadline option 
make: *** [Makefile.common:181: common-lint] Error 4`

Please include more info about prerequisites for a succesful compilation.

**Comment by royvandongen** [comment]
Apparently a `go build nginx_rtmp_exporter.go` did the thing, still a bit of documentation would be awesome!

**Comment by mauricioabreu** [comment]
Hello, @royvandongen thank you for the report.
I am on macOS so this is the reason I did not try on Ubuntu. I will investigate it later and provide better docs.

**Comment by royvandongen** [comment]
Please consider also making Prometheus template available. Default Prometheus config does not seem to handle all information.

**Comment by mauricioabreu** [comment]
Do you mind to send a pull request? @royvandongen
