### ISSUE TITLE
clients count per stream

### ISSUE THREAD

**Issue by genofire** [mauricioabreu/nginx_rtmp_prometheus#6]

**Comment by mauricioabreu** [comment]
Is this a feature? Bug?

**Comment by genofire** [comment]
sorry for that delay - I would like to have metric, with client cound per stream as feature:
```
# Count of RTMP clients of Stream
nginx_rtmp_stream_clients_count{stream="stream_hello"} 2
nginx_rtmp_stream_clients_count{stream="hls_hello_360p878kbs"} 1
nginx_rtmp_stream_clients_count{stream="hls_hello_240p264kbs"} 1
nginx_rtmp_stream_clients_count{stream="hls_hello_240p528kbs"} 1
nginx_rtmp_stream_clients_count{stream="hls_hello_720p2628kbs"} 1
nginx_rtmp_stream_clients_count{stream="hls_hello_480p1128kbs"} 1
```

**Comment by mauricioabreu** [comment]
@genofire sorry for the delay. I'm currently out of time to implement this but I don't think it is hard to add if you know some golang. I can help you anyways

**Comment by genofire** [comment]
i am switching to OvenMediaEngine -> there i write an Exporter:
https://dev.sum7.eu/genofire/oven-exporter

so i do not need it anymore

**Comment by genofire** [comment]
@mauricioabreu okay, youself has no Interesses on this feature?

**Comment by mauricioabreu** [comment]
@genofire someone I don't know forked this repo and did this feature a week ago. I have been waiting for this person to make a pull request to my repository with this feature

https://github.com/summittech-ca/nginx_rtmp_prometheus
