### ISSUE TITLE
Bug in Traffic

### ISSUE THREAD

**Issue by genofire** [mauricioabreu/nginx_rtmp_prometheus#7]
the nginx-rtmp shows MB/s but exporter just B/s - 

--- 

there are several:
```golang
	bandwidthInNum = n / 1048576 // bandwidth is in bits
```

should it be replaced by
```golang
	bandwidthInNum = n * 1048576 // bandwidth is in bits
```

???

**Comment by mauricioabreu** [comment]
I think this comment could be improved but it means "NGINX-RTMP saves this metric as bits and we need to convert to bytes"
